name: Continous Integration

on:
  push:
    branches:
      - main
      - production
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - production
      - develop

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🧑🏻‍💻 Checkout code
        uses: actions/checkout@v3

      - name: 🥷 Setup node and bun
        uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: lts/hydrogen
          check-latest: true

      - name: 🎪 Install dependencies
        run: bun install --immutable

      - name: 🛠️ Build
        run: bun run build:app

      - name: 🚑 Typecheck
        run: bun typecheck

      - name: 🔬 Lint
        run: bun lint
