name: Continous Integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - develop

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🧑🏻‍💻 Checkout code
        uses: actions/checkout@v3

      - name: 🥷 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          check-latest: true
          cache: "yarn"

      - name: 🎪 Install dependencies
        run: yarn install --immutable

      - name: 🧪 Yarn check cache
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: yarn install --check-cache

      - name: 🚑 Typecheck
        run: yarn typecheck

      - name: 🔬 Lint
        run: yarn lint

      - name: 🛠️ build
        run: yarn build
